// software_dev/javascript/vue.js/todo-list/src/components/Login.vue
<template>
  <div class="login-container">
    <div class="login-form">
      <h1>Todo App Login</h1>
      
      <form @submit.prevent="handleLogin">
        <div class="form-group">
          <label for="username">Username</label>
          <input id="username" v-model="username" placeholder="Enter username" required />
        </div>
        
        <div class="form-group">
          <label for="password">Password</label>
          <input id="password" v-model="password" type="password" placeholder="Enter password" required />
        </div>
        
        <button type="submit" class="btn btn-primary">Login</button>
        
        <div v-if="errorMessage" class="error-message">
          {{ errorMessage }}
        </div>
      </form>
      
      <div class="demo-info">
        <p><strong>Demo users:</strong></p>
        <p>Username: <code>one</code> | Password: <code>one</code></p>
        <p>Username: <code>two</code> | Password: <code>two</code></p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, inject } from 'vue'
import { useRouter } from 'vue-router'

const username = ref('')
const password = ref('')
const errorMessage = ref('')
const router = useRouter()
const auth = inject<any>('auth')!

const handleLogin = () => {
  errorMessage.value = ''
  
  if (auth.login(username.value, password.value)) {
    router.push('/')
  } else {
    errorMessage.value = 'Invalid username or password'
    password.value = ''
  }
}
</script>

// software_dev/javascript/react/todo_list/src/components/Login.tsx
import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../context'

const Login: React.FC = () => {
    const [username, setUsername] = useState('')
    const [password, setPassword] = useState('')
    const [errorMessage, setErrorMessage] = useState('')
    const navigate = useNavigate()
    const auth = useAuth()

    const handleLogin = (e: React.FormEvent) => {
        e.preventDefault()
        setErrorMessage('')

        if (auth.login(username, password)) {
            navigate('/')
        } else {
            setErrorMessage('Invalid username or password')
            setPassword('')
        }
    }

    return (
        <div className="login-container">
            <div className="login-form">
                <h1>Todo App Login</h1>

                <form onSubmit={handleLogin}>
                    <div className="form-group">
                        <label htmlFor="username">Username</label>
                        <input
                            id="username"
                            value={username}
                            onChange={(e) => setUsername(e.target.value)}
                            placeholder="Enter username"
                            required
                        />
                    </div>

                    <div className="form-group">
                        <label htmlFor="password">Password</label>
                        <input
                            id="password"
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                            type="password"
                            placeholder="Enter password"
                            required
                        />
                    </div>

                    <button type="submit" className="btn btn-primary">Login</button>

                    {errorMessage && (
                        <div className="error-message">
                            {errorMessage}
                        </div>
                    )}
                </form>

                <div className="demo-info">
                    <p><strong>Demo users:</strong></p>
                    <p>Username: <code>one</code> | Password: <code>one</code></p>
                    <p>Username: <code>two</code> | Password: <code>two</code></p>
                </div>
            </div>
        </div>
    )
}

export default Login
